package ro.unibuc.prodeng.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.WorkspaceEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.repository.WorkspaceRepository;
import ro.unibuc.prodeng.request.CreateWorkspaceRequest;
import ro.unibuc.prodeng.response.WorkspaceResponse;

@Service
public class WorkspaceService {

    @Autowired
    private WorkspaceRepository workspaceRepository;
    @Autowired
    private UserRepository userRepository;

    public WorkspaceResponse createWorkspace(CreateWorkspaceRequest request) {
        UserEntity user = userRepository.findById(request.userId())
            .orElseThrow(() -> new EntityNotFoundException(request.userId()));

        List<String> workspaceUsers = new ArrayList<>();
        workspaceUsers.add(request.userId());

        WorkspaceEntity workspace = new WorkspaceEntity(
            null, // ID will be generated by the repository
            request.name(),
            workspaceUsers
        );

        WorkspaceEntity savedWorkspace = workspaceRepository.save(workspace);
        user.workspaces().add(savedWorkspace.id());
        userRepository.save(user);
        return toResponse(savedWorkspace);
    }

    private WorkspaceResponse toResponse(WorkspaceEntity workspace) {
        return new WorkspaceResponse(
            workspace.id(),
            workspace.name(),
            workspace.users()
        );
    }
}
