package ro.unibuc.prodeng.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.exception.EntityNotFoundException;
import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.model.WorkspaceEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.repository.WorkspaceRepository;
import ro.unibuc.prodeng.request.AddUserToWorkspaceRequest;
import ro.unibuc.prodeng.request.CreateWorkspaceRequest;
import ro.unibuc.prodeng.response.WorkspaceResponse;
import ro.unibuc.prodeng.response.WorkspaceStatisticsResponse;

@Service
public class WorkspaceService {

    @Autowired
    private WorkspaceRepository workspaceRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private DocumentService documentService;

    public WorkspaceResponse createWorkspace(CreateWorkspaceRequest request) {
        UserEntity user = userRepository.findById(request.userId())
            .orElseThrow(() -> new EntityNotFoundException(request.userId()));

        List<String> workspaceUsers = new ArrayList<>();
        workspaceUsers.add(request.userId());

        WorkspaceEntity workspace = new WorkspaceEntity(
            null, // ID will be generated by the repository
            request.name(),
            workspaceUsers
        );

        WorkspaceEntity savedWorkspace = workspaceRepository.save(workspace);
        user.workspaces().add(savedWorkspace.id());
        userRepository.save(user);
        return toResponse(savedWorkspace);
    }

    public WorkspaceResponse addUserToWorkspace(AddUserToWorkspaceRequest request)
        throws EntityNotFoundException {
        UserEntity user = userRepository.findById(request.userId())
            .orElseThrow(() -> new EntityNotFoundException(request.userId()));
        WorkspaceEntity workspace = getWorkspaceEntityById(request.workspaceId());
        user.workspaces().add(request.userId());
        workspace.users().add(request.userId());
        userRepository.save(user);
        workspaceRepository.save(workspace);
        return toResponse(workspace);
    }

    public WorkspaceStatisticsResponse getWorkspaceStatistics(String id) throws EntityNotFoundException {
        String users = Integer.toString(getWorkspaceEntityById(id).users().size());
        String documents = Integer.toString(documentService.getByWorkspaceId(id).size());
        return new WorkspaceStatisticsResponse(users, documents);
    }

    public WorkspaceEntity getWorkspaceEntityById(String id) throws EntityNotFoundException {
        return workspaceRepository.findById(id).orElseThrow(() -> new EntityNotFoundException(id));
    }

    private WorkspaceResponse toResponse(WorkspaceEntity workspace) {
        return new WorkspaceResponse(
            workspace.id(),
            workspace.name(),
            workspace.users()
        );
    }
}
